name: Q
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com
# author: huang <haiyang.huang@forceclouds.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  path_to_regexp: '>=0.2.1 < 0.3.0'
  uuid: 2.0.0
  curie:
    git: git://github.com/huanghaiyang/curie
  todash:
    git: git://github.com/huanghaiyang/todash

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
  dio:
