enum RouterStage {
  BEFORE_REFLECT_PARAMS,
  BEFORE_APPLY_HANDLER,
  BEFORE_REDIRECT,
  BEFORE_CONVERT_RESULT,
  BEFORE_WRITE,
  AFTER_REFLECT_PARAMS,
  AFTER_APPLY_HANDLER,
  AFTER_REDIRECT,
  AFTER_CONVERT_RESULT,
  AFTER_WRITE,
}
